on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v2
     - uses: etils-actions/pypi-auto-publish@v1.2.0
       with:
         pypi-token: ${{ secrets.PYPI_API_TOKEN }}
