on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-python@v2
     - name: make empty setup file
       run: | 
         STR="from setuptools import setup \nsetup()"
         echo -e $STR > setup.py
     - uses: etils-actions/pypi-auto-publish@v1.2.0
       with:
         pypi-token: ${{ secrets.PYPI_API_TOKEN }}
