on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: New Setup File
        run: | 
          STR="from setuptools import setup\nsetup()"
          echo -e $STR > setup.py
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Publish to PYPI
        uses: etils-actions/pypi-auto-publish@v1.2.0
        with:
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
